site_name: Harvard Research Computing Trusted Research Environment
site_url: https://foromeplatform.github.io/tre/
repo_url: https://github.com/ForomePlatform/tre
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs          # top-level tabs
    - navigation.sections      # grouped left sidebar per tab
    - navigation.expand        # auto-expand current section
    - navigation.top           # sticky header + back-to-top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  icon:
    logo: material/library
    repo: fontawesome/brands/github

extra_css:
  - assets/harvard.css

nav:
  - Overview: index.md
#  - Background:
#      - Data Preparation for Pattern recognition: assets/slides/background/index.html
  - Trust:
      - Data Provenance and Compliance: trust/index.md
  - Research:
      - Tools and Lifecycle: research/index.md
  - Environment:
      - Deployment Blueprint: environment/deployment-blueprint.md
  - Reference Case:
      - Project Overview: reference-case/project-overview.md
  - Team: team/index.md

plugins:
  - search
  - autorefs
  - glightbox
  - minify:
      minify_html: true
#  - revealjs:
#      transition: slide   # or fade, convex, concave, none https://revealjs.com/transitions/

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details          # enables ??? collapsible blocks
  - pymdownx.superfences      # code fences inside details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ForomePlatform/tre
      name: GitHub repo
